package Free;

import static org.junit.Assert.*;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

public class ChinaAndInternationalTest {

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
	}

	@Test
	public void test() {
		String ActualResult;
		String ExpectResult;
		/**
		 * 国内测试
		 **/
		//测试第1个参数--空格
				ChinaAndInternational test1=new ChinaAndInternational();
				ActualResult=test1.Compute("",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--数字
				ActualResult=test1.Compute("1",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--字母
				ActualResult=test1.Compute("a",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--错误输入
				ActualResult=test1.Compute("任正飞",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第2个参数--错误输入
				ActualResult=test1.Compute("中国",-1,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第4个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,-1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第5个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,-1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第6个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,1,-1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--空格
				ActualResult=test1.Compute("中国",12,1,1,1,1,"");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--数字
				ActualResult=test1.Compute("中国",12,1,1,1,1,"1");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--字母
				ActualResult=test1.Compute("中国",12,1,1,1,1,"a");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--错误输入
				ActualResult=test1.Compute("中国",12,1,1,1,1,"任正飞");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
				
				/**
				 * 区域一测试
				 **/
		//测试第1个参数--空格
				ActualResult=test1.Compute("",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--数字
				ActualResult=test1.Compute("1",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--字母
				ActualResult=test1.Compute("a",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--错误输入
				ActualResult=test1.Compute("任正飞",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第2个参数--错误输入
				ActualResult=test1.Compute("中国",-1,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第4个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,-1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第5个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,-1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第6个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,1,-1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--空格
				ActualResult=test1.Compute("中国",12,1,1,1,1,"");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--数字
				ActualResult=test1.Compute("中国",12,1,1,1,1,"1");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--字母
				ActualResult=test1.Compute("中国",12,1,1,1,1,"a");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--错误输入
				ActualResult=test1.Compute("中国",12,1,1,1,1,"任正飞");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
				/**
				 * 区域二测试
				 **/
		//测试第1个参数--空格
				ActualResult=test1.Compute("",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--数字
				ActualResult=test1.Compute("1",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--字母
				ActualResult=test1.Compute("a",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--错误输入
				ActualResult=test1.Compute("任正飞",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第2个参数--错误输入
				ActualResult=test1.Compute("中国",-1,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第4个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,-1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第5个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,-1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第6个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,1,-1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--空格
				ActualResult=test1.Compute("中国",12,1,1,1,1,"");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--数字
				ActualResult=test1.Compute("中国",12,1,1,1,1,"1");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--字母
				ActualResult=test1.Compute("中国",12,1,1,1,1,"a");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--错误输入
				ActualResult=test1.Compute("中国",12,1,1,1,1,"任正飞");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
				/**
				 * 区域三测试
				 **/
		//测试第1个参数--空格
				ActualResult=test1.Compute("",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--数字
				ActualResult=test1.Compute("1",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--字母
				ActualResult=test1.Compute("a",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--错误输入
				ActualResult=test1.Compute("任正飞",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第2个参数--错误输入
				ActualResult=test1.Compute("中国",-1,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第4个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,-1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第5个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,-1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第6个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,1,-1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--空格
				ActualResult=test1.Compute("中国",12,1,1,1,1,"");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--数字
				ActualResult=test1.Compute("中国",12,1,1,1,1,"1");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--字母
				ActualResult=test1.Compute("中国",12,1,1,1,1,"a");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--错误输入
				ActualResult=test1.Compute("中国",12,1,1,1,1,"任正飞");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
				/**
				 * 区域四测试
				 **/
		//测试第1个参数--空格
				ActualResult=test1.Compute("",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--数字
				ActualResult=test1.Compute("1",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--字母
				ActualResult=test1.Compute("a",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--错误输入
				ActualResult=test1.Compute("任正飞",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第2个参数--错误输入
				ActualResult=test1.Compute("中国",-1,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第4个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,-1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第5个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,-1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第6个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,1,-1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--空格
				ActualResult=test1.Compute("中国",12,1,1,1,1,"");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--数字
				ActualResult=test1.Compute("中国",12,1,1,1,1,"1");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--字母
				ActualResult=test1.Compute("中国",12,1,1,1,1,"a");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--错误输入
				ActualResult=test1.Compute("中国",12,1,1,1,1,"任正飞");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
				/**
				 * 韩国测试
				 **/
		//测试第1个参数--空格
				ActualResult=test1.Compute("",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--数字
				ActualResult=test1.Compute("1",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--字母
				ActualResult=test1.Compute("a",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--错误输入
				ActualResult=test1.Compute("任正飞",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第2个参数--错误输入
				ActualResult=test1.Compute("中国",-1,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第4个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,-1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第5个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,-1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第6个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,1,-1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--空格
				ActualResult=test1.Compute("中国",12,1,1,1,1,"");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--数字
				ActualResult=test1.Compute("中国",12,1,1,1,1,"1");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--字母
				ActualResult=test1.Compute("中国",12,1,1,1,1,"a");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--错误输入
				ActualResult=test1.Compute("中国",12,1,1,1,1,"任正飞");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
				/**
				 * 特别旅客测试
				 **/
		//测试第1个参数--空格
				ActualResult=test1.Compute("",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--数字
				ActualResult=test1.Compute("1",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--字母
				ActualResult=test1.Compute("a",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第1个参数--错误输入
				ActualResult=test1.Compute("任正飞",12,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第2个参数--错误输入
				ActualResult=test1.Compute("中国",-1,1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第3个参数--错误输入
				ActualResult=test1.Compute("中国",1,-1,1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第4个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,-1,1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第5个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,-1,1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第6个参数--错误输入
				ActualResult=test1.Compute("中国",1,1,1,1,-1,"经济舱");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--空格
				ActualResult=test1.Compute("中国",12,1,1,1,1,"");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--数字
				ActualResult=test1.Compute("中国",12,1,1,1,1,"1");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--字母
				ActualResult=test1.Compute("中国",12,1,1,1,1,"a");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
		//测试第7个参数--错误输入
				ActualResult=test1.Compute("中国",12,1,1,1,1,"任正飞");
				ExpectResult="error";
				assertSame(ActualResult,ExpectResult);
	}
}
